# Generated by Django 5.0 on 2024-01-08 09:30

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=product.models.upload_to_path, verbose_name='image'),
        ),
    ]
