# Generated by Django 5.0 on 2024-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='percentage',
            field=models.PositiveSmallIntegerField(verbose_name='percentage'),
        ),
    ]
