# Generated by Django 5.0 on 2024-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_compound_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='previous price'),
        ),
    ]
