# Generated by Django 5.0 on 2024-01-07 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.PositiveIntegerField(default=0)),
                ('online', models.PositiveIntegerField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('mid_rate', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'clients info',
                'verbose_name_plural': 'clients info',
                'db_table': 'clients_info',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='company/photos/')),
                ('html_page', models.FileField(blank=True, null=True, upload_to='company/pages/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'company info',
                'verbose_name_plural': 'company info',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, default="Terra Pro: Clothing store in Tashkent ≡ Men's and women's clothing on Terrapro.uz", max_length=128)),
                ('site_icon', models.ImageField(upload_to='info/site/')),
                ('site_description', models.TextField(blank=True, default="Terra Pro - Manufacturer of men's and women's clothing at competitive prices ⭐️ Clothing store in Uzbekistan ✔️ Trying on and fast delivery of clothes ☎ +998 71 2509391 | Clothing store Terrapro.uz")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'site info',
                'verbose_name_plural': 'site info',
                'db_table': 'site_info',
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'working time',
                'verbose_name_plural': 'working times',
                'db_table': 'working_time',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_contacts', to='account.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='home.siteinfo')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='SiteReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.siteinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Review',
                'verbose_name_plural': 'Site Reviews',
                'db_table': 'site_review',
            },
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='work_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_info', to='home.workingtime', verbose_name='work time'),
        ),
    ]
